### ISSUE TITLE
Incorrect copy natives task deps

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-browser-natives#10]
Copy tasks should depend on build tasks, because at the moment they copy before build.

**Comment by AlexanderMoskovkin** [comment]
The 'copy-win-natives' task depends on 'build-win-natives', it's ok here.
'build-mac-natives' and 'copy-mac-natives' work with different files. The 'build-mac-natives' task builds Objective C files to the bin path and the 'copy-mac-natives' task copies apple script files (we don't build them). So, we can run tasks asynchronously when they both depend on clean-task.

**Comment by inikulin** [comment]
Ok, I see now. Then I think we should choose more obvious naming for tasks:

`clean-win-natives` -> `clean-win-bin`
`build-win-natives` -> `build-win-executables`
`copy-win-natives` -> `copy-win-executables`
`clean-mac-natives` -> `clean-mac-bin`
`build-mac-natives` -> `build-mac-executables`
`copy-mac-natives` -> `copy-mac-scripts`

BTW, if we `copy-win-natives` depends on `build-win-natives` we don't need `build-win` task to depend on `build-win-natives`: https://github.com/superroma/testcafe-browser-natives/blob/master/Gulpfile.js#L96

We can pass `callback` directly to `catch` here: https://github.com/superroma/testcafe-browser-natives/blob/master/Gulpfile.js#L54
