### ISSUE TITLE
Prepare NPM publish

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-browser-natives#14]
We need to publish it to NPM, so it can be used by TestCafe package. Fill required `package.json` fields: description, name, author, copyrights, version, etc.

**Comment by AlexanderMoskovkin** [comment]
Should we write all of us to the "contributors" field or just write @superroma as an author?

**Comment by inikulin** [comment]
Developer Express Inc. as an author, all of us as contributors with corporate emails.
