### ISSUE TITLE
Consider using JSDOC for the internal package APIs

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-browser-natives#16]
I think we should use [JSDOC](http://usejsdoc.org/) comments and autogenerated docs for internal packages (browser-natives, hammerhead).

It will somehow help us keep things in sync and we will have ability to determine if given function is the public API for this package (it's really helpful for the Hammerhead client API).

Moreover, I think we should move dev information to the wiki pages of the projects and just leave short logo, short description link to the dev docs in repo wiki and copyrights in README. 
Everything else (like design docs, API reference, test instructions) should be kept in wiki pages.
/cc @VasilyStrelyaev @MargaritaLoseva  @AlexanderMoskovkin @churkin @kirovboris

**Comment by inikulin** [comment]
BTW we can generate markdown from jsdoc: https://www.npmjs.com/package/jsdoc-to-markdown

**Comment by AlexanderMoskovkin** [comment]
I like the idea to use JSDOC.

**Comment by AndreyBelym** [comment]
Excellent idea! Also should be noted, that JSDoc2MD has official integration with Gulp: https://www.npmjs.com/package/gulp-jsdoc-to-markdown

**Comment by VasilyStrelyaev** [comment]
Cool! I like it

**Comment by kirovboris** [comment]
Looks pretty good

**Comment by inikulin** [comment]
Ok, then @AlexanderMoskovkin @AndreyBelym can you add JSDOC comments for this package and create corresponding gulp task?

**Comment by AlexanderMoskovkin** [comment]
sure

**Comment by inikulin** [comment]
So they current idea is (we've discussed shortly with guys in person): 
1)Keep everything in README.md 
2)Move API to autogenerated API.md and reference it from README.md's API section.

**Comment by inikulin** [comment]
Closed via #30
