### ISSUE TITLE
Update eslint to v1.0.0

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-browser-natives#22]

**Comment by inikulin** [comment]
We have eslint/eslint#3226 now. Waiting for fix. :weary:

**Comment by AndreyBelym** [comment]
eslint/eslint#3226 has been fixed in 1.2.0, but I've discovered an another issue: https://github.com/eslint/eslint/issues/3463

**Comment by inikulin** [comment]
It's already fixed, so let's wait for 1.3.0 =)

**Comment by inikulin** [comment]
We can switch now. Things to do on switch:
1. Switch `curly` rule to the `multi-or-nest` mode and set warning level to `2`.
2. Remove conditional comments which disabled buggy `indent`.

See also: superroma/testcafe-phoenix#43

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym we were waiting for the https://github.com/eslint/eslint/issues/3463 fix and it was fixed in the 1.2.1 version (it's published now), so it seems we can switch now.

**Comment by AndreyBelym** [comment]
Yes, sure, one moment please.
