### ISSUE TITLE
Fix npm license warning

### ISSUE THREAD

**Issue by AndreyBelym** [superroma/testcafe-browser-natives#37]
npm gives a warning when installing our package: `license should be a valid SPDX license expression` ([example](https://travis-ci.org/superroma/testcafe-browser-natives/jobs/81394098#L97)). By now we have set `license` field in `package.json` to hyperref of license file in repo, but [npm documentation](https://docs.npmjs.com/files/package.json#license) suggests following expression:

If you are using a license that hasn't been assigned an SPDX identifier, or if you are using a custom license, use the following valid SPDX expression:
```
{ "license" : "SEE LICENSE IN <filename>" }
```

**Comment by AlexanderMoskovkin** [comment]
If we will follow the recommendation the `packaje.json` file will contain:
`{ "license": "SEE LICENSE IN LICENSE" }`
Looks ugly. Otherwise we have the warning as @AndreyBelym wrote above.

@inikulin what do you think?

**Comment by inikulin** [comment]
@AlexanderMoskovkin nah, just fine for now. We use temporary license anyway.

**Comment by inikulin** [comment]
closed via #32
