### ISSUE TITLE
Release new version to NPM

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-browser-natives#38]

**Comment by AlexanderMoskovkin** [comment]
The current version is `0.9.1`
The new API function was added in the https://github.com/superroma/testcafe-browser-natives/issues/42 issue. Should we update the version to the `0.10.0` (as we do in the `testcafe-hammerhead` repo) or increase just the last number (`0.9.2`) while we don't release `testcafe-phoenix`? /cc @inikulin

**Comment by inikulin** [comment]
Follow semver. It should be 0.10.0. We have a 2.0.0 hammerhead release next week )))
