### ISSUE TITLE
Implement getBrowserInfo api function

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-browser-natives#42]
`getBrowserInfo(browser)`

where `browser` is a string:

- if it's an `browser alias` (like `chrome` or `ie`) just return the information from `getInstallations` for this alias;
- if it's a file path check file existing. Then check the path with regexp to find some browser alias in there. If found, get the `browserInfo` structure (cmd, templates) from `getInstallations` by the alias and return it with current path. If not found return default browser info (for example with something like `start filePath` for windows etc.)

**Comment by AndreyBelym** [comment]
I'm working on it.
